// <auto-generated />
namespace Prototype.DocuSign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddSenderInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSenderInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201405211919504_AddSenderInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
